title: 淳粹生活
baseurl: ""
url: "https://chunslifestyle.github.io"
theme: minima
plugins:
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: default
    tag: default
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
